{{- if .Values.pro.enabled -}}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filterpolicies.getambassador.io
  annotations:
    "helm.sh/hook": crd-install
  {{ if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
  {{ end }}
spec:
  group: getambassador.io
  version: v1beta2
  versions:
  - name: v1beta2
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: filterpolicies
    singular: filterpolicy
    kind: FilterPolicy
    shortNames:
    - fp
{{- end -}}
