{{- if and .Values.licenseKey.createSecret (contains "datawire-dev/aes" .Values.image.repository) }}
apiVersion: v1
kind: Secret
metadata:
  name: ambassador-edge-stack
  namespace: {{ include "ambassador.namespace" . }}
type: Opaque
data:
  license-key: {{- if .Values.licenseKey.value }} {{ .Values.licenseKey.value | b64enc }} {{- else }} "" {{- end }}
{{- end }}